# Generated by Django 6.0 on 2025-12-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images')),
                ('rating', models.IntegerField()),
                ('relese_date', models.DateField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, null=True, to='movies.genre')),
            ],
        ),
    ]
