# Generated by Django 6.0 on 2025-12-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='hero_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
