# Generated by Django 6.0 on 2025-12-23 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_reviews_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='movie_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_name', to='movies.movies'),
        ),
    ]
