# Generated by Django 6.0 on 2025-12-24 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_register_user_delete_user'),
        ('movies', '0005_alter_reviews_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faviorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faviorite_by', to='movies.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faviorites', to='accounts.register_user')),
            ],
            options={
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
