# Generated by Django 6.0 on 2025-12-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_faviorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faviorites',
        ),
    ]
