# Generated by Django 6.0 on 2025-12-25 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_faviorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('problem', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='faviorites',
            unique_together={('user', 'movie')},
        ),
    ]
